### ISSUE TITLE
Núcleo Gestor

### ISSUE THREAD

**Issue by severoemanuel** [Emanuel-Soares/eeepjaa#11]
# Conteúdo
- Margareth
- Monique
- Lucilene
- Eduardo
- Rosa

**Comment by diego-nac** [comment]
Pessoas inseridas e feito a fatoração da área. Commit "Adicionado o nome dos gestores e finalizado a área"

**Comment by severoemanuel** [comment]
Falta melhorar a responsividade. No meu celular a imagem estava sobrepondo o texto
